# Generated by Django 5.0.6 on 2024-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorsbooks', '0002_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='authorsbooks.author'),
        ),
    ]
